name: ZAP Security Scan

on:
  workflow_dispatch:  # دستی اجرا میشه

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: 'https://آدرس-سایت-مورد-نظر.com'
          report_html: 'zap-report.html'
          fail_action: false

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-security-report
          path: zap-report.html
